baseURL = 'https://hack3d.blog/'
languageCode = 'en-us'
title = 'hack3d.blog'
theme = "ananke"

googleAnalytics = "G-LVTLQ50FTJ"

[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'
