apiVersion: v1
kind: Service
metadata:
  name: {{ include "blog.fullname" . }}
  labels:
    {{- include "blog.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalName: {{ .Values.service.externalName }}
  selector:
    {{- include "blog.selectorLabels" . | nindent 4 }}
