name: Build and Deploy

on:
  push:
    # branches: [main]

concurrency: ci-${{ github.ref }}

env:
  assets-bucket: hack3d-assets

jobs:
  helm:
    runs-on: ubuntu-latest
    name: Deploy Blog Helm chart
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - name: Install helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash -
      - run: ls -la 
      - name: Deploy helm chart
        working-directory: charts
        run: helm upgrade --install blog blog
  assets:
    runs-on: ubuntu-latest
    name: Build and Deploy Blog Assets
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true # fetch hugo themes
      - run: python -m pip install s3cmd
      - name: Cache build output
        id: build-cache
        uses: actions/cache@v3
        with:
          path: public/**
          key: blog-build-${{ hashFiles('**') }}
      - name: Setup Hugo
        if: steps.build-cache.outputs.cache-hit != 'true'
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.102.3'
      - name: Build Assets
        if: steps.build-cache.outputs.cache-hit != 'true'
        run: hugo --minify
      - name: Deploy Assets
        run: |
            s3cmd \
              --host=us-east-1.linodeobjects.com \
              --host-bucket="%(bucket)s.us-east-1.linodeobjects.com" \
              --no-mime-magic \
              --no-delete-removed \
              --acl-public \
              sync \
              public/* \
              s3://${{ env.assets-bucket }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}